"""initial_schema

Revision ID: 678705771ddf
Revises: 
Create Date: 2025-11-21 16:00:23.224416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '678705771ddf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contacts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('repo_link', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('resumes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stacks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('proficiency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stacks_name'), 'stacks', ['name'], unique=True)
    op.create_table('testimonials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_name', sa.String(), nullable=False),
    sa.Column('author_url', sa.String(), nullable=True),
    sa.Column('author_avatar_url', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_experiences',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('company_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contact_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'language_code', name='uq_contact_translation_lang')
    )
    op.create_table('project_stacks',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('stack_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'stack_id')
    )
    op.create_table('project_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('role', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'language_code', name='uq_project_translation_lang')
    )
    op.create_table('testimonial_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('testimonial_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('author_position', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['testimonial_id'], ['testimonials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('testimonial_id', 'language_code', name='uq_testimonial_translation_lang')
    )
    op.create_table('work_experience_stacks',
    sa.Column('work_experience_id', sa.Uuid(), nullable=False),
    sa.Column('stack_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['stack_id'], ['stacks.id'], ),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experiences.id'], ),
    sa.PrimaryKeyConstraint('work_experience_id', 'stack_id')
    )
    op.create_table('work_experience_translations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('work_experience_id', sa.Uuid(), nullable=False),
    sa.Column('language_code', sa.String(length=10), nullable=False),
    sa.Column('position', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['work_experience_id'], ['work_experiences.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_experience_id', 'language_code', name='uq_work_exp_translation_lang')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_experience_translations')
    op.drop_table('work_experience_stacks')
    op.drop_table('testimonial_translations')
    op.drop_table('project_translations')
    op.drop_table('project_stacks')
    op.drop_table('contact_translations')
    op.drop_table('work_experiences')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_stacks_name'), table_name='stacks')
    op.drop_table('stacks')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('contacts')
    # ### end Alembic commands ###
